language: java
jdk: oraclejdk8
python:
  - "3.6"
script:
  - cd tools
  - ant test
notifications:
  email:
    recipients:
      - jonathan.aldrich@cs.cmu.edu
group: deprecated-2017Q1        # try to work around TravisCI update that breaks ant junit task